### ISSUE TITLE
关于“论文撰写使用Word或LaTeX(建议优先使用LaTeX)实现排版”

### ISSUE THREAD

**Issue by Marukon** [registor/nwafuthesis#2]
- 首先感谢老师提供的latex模板，方便了广大学子。
 - 在《本科毕业论文（设计）写作规范》(试用)第十三条中“排版工具”中，提到“论文撰写使用Word或LaTeX(建议优先使用LaTeX)实现排版”私以为不妥。
 - LaTex无疑是一个优雅的排版工具，尤其针对包含大量公式的理工科而言，然而就好像是命令行和GUI之间的“战争”一样，Word和LaTex也是究竟谁好也一个永恒的话题。
 - 针对我校人文等学科，LaTexp排版几乎没有太大必要，提供一个更好的word模板似乎更加实用一些。
 - 因此建议在试行的写作规范中去掉“(建议优先使用LaTeX)”，望慎重考虑，谢谢。

**Comment by registor** [comment]
这个建议与我无关 谢谢！   耿楠 西北农林科技大学信息工程学院 712100 陕西杨凌西农路22号 电话：029-87092352 邮箱：nangeng@nwsuaf.edu.cn            nangeng@qq.com   Geng Nan College of Information Engineering Northwest A&F University Shaanxi Yangling China 712100 Tel: 8602987092352 Email: nangeng@nwsuaf.edu.cn            nangeng@qq.com编辑删除 在2019年04月15日 17:58，Maruko 写道： 首先感谢老师提供的latex模板，方便了广大学子。在《本科毕业论文（设计）写作规范》(试用)第十三条中“排版工具”中，提到“论文撰写使用Word或LaTeX(建议优先使用LaTeX)实现排版”私以为不妥。LaTex无疑是一个优雅的排版工具，尤其针对理工科而言，然而就好像是命令行和GUI之间的“战争”一样，Word和LaTex也是究竟谁好也一个永恒的话题。针对我校人文等学科，LaTexp排版几乎没有太大必要，提供一个更好的word模板似乎更加实用一些。因此建议在试行的写作规范中去掉“(建议优先使用LaTeX)”，望慎重考虑，谢谢。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by registor** [comment]
同学，你好： 非常感谢你对该LaTeX模板的关注，关于你提到的人文等学科的论文没必要使用LaTeX排版，提供一个Word模板更为实用的说法， 我觉得至少在如下几个方面值得商榷： (1)排版规范性的问题 众所周知，论文排版，特别是毕业论文的排版，重要的是“规范”，是符合标准。LaTeX排版，是强制遵守“规范”，不严格遵守规范，往往得不到排版结果。而由于Word排版，即便是不用规定的字体、字号、段前段后、行距、文献引注著录标准也可以得到一个“相似”的排版结果。 (2)模板的易用性问题 由于LaTeX采用的是“格式与内容分离”的思想，将主要的格式与规范和标准封装在模板中，留给用户的是设计好的接口，因此，只需要使用指定的命令便可以方便的实现排版要求。但Word的模板往往很难做到这一点，多数情况下，只是在简单地使用格式刷，Word模板名存实亡。并且，多数情况下，多数用户会将Word排版规定和排版样例误认为是Word模板。 (3)学习成本的问题 诚然，LaTeX的学习曲线比较陡峭，这是一个不争的事实，但只要认真去学习，也不是想象的难么难。反观Word，大家认为容易学，主要是因为基本不用Word的样式、交叉引用、域代码、文献管理等第三方插件等高级功能，而这些，在毕业论文排版中又往往是必须的功能。事实证明，对于Word的这些高级功能，起学习曲线也异常陡峭，并且学了也不一定会用。 (4)排版过程及结果稳定性的问题 LaTeX排版系统的稳定性是经过了历史验证的，其排版结果是PDF格式的文件，不存在倒版倒平台问题，无论在自己电脑、导师电脑、打印部电脑上，还是手机、平板上，其表现出的结果都是一致的。而Word往往会出现文件打不开、倒版倒平台格式变化的问题，这在不断要修改的毕业论文排版中，往往会带来很多的烦心事。 (5)关于版权的问题 众所周知，LaTeX是一套免费的排版系统，不存在版权问题。而Word是收费软件，也许某个电脑是安装的是正版Office，但类似打印部等其他电脑上可能盗版居多，这也是一个不争的事实。 因此，我个人认为，人文等学科的毕业论文更是有必要使用LaTeX排版，以避免由于Word使用不精导致的排版不标准、不规范，以及后期修订所带来的各种各样的问题。 这些只代表我个人看法，与官方“通知”无关。 谢谢！   耿楠 西北农林科技大学信息工程学院 712100 陕西杨凌西农路22号 电话：029-87092352 邮箱：nangeng@nwsuaf.edu.cn            nangeng@qq.com   Geng Nan College of Information Engineering Northwest A&F University Shaanxi Yangling China 712100 Tel: 8602987092352 Email: nangeng@nwsuaf.edu.cn            nangeng@qq.com编辑删除 在2019年04月15日 18:59，耿楠 写道： 这个建议与我无关 谢谢！   耿楠 西北农林科技大学信息工程学院 712100 陕西杨凌西农路22号 电话：029-87092352 邮箱：nangeng@nwsuaf.edu.cn            nangeng@qq.com   Geng Nan College of Information Engineering Northwest A&F University Shaanxi Yangling China 712100 Tel: 8602987092352 Email: nangeng@nwsuaf.edu.cn            nangeng@qq.com编辑删除 在2019年04月15日 17:58，Maruko 写道： 首先感谢老师提供的latex模板，方便了广大学子。在《本科毕业论文（设计）写作规范》(试用)第十三条中“排版工具”中，提到“论文撰写使用Word或LaTeX(建议优先使用LaTeX)实现排版”私以为不妥。LaTex无疑是一个优雅的排版工具，尤其针对理工科而言，然而就好像是命令行和GUI之间的“战争”一样，Word和LaTex也是究竟谁好也一个永恒的话题。针对我校人文等学科，LaTexp排版几乎没有太大必要，提供一个更好的word模板似乎更加实用一些。因此建议在试行的写作规范中去掉“(建议优先使用LaTeX)”，望慎重考虑，谢谢。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Marukon** [comment]
感谢耿老师的耐心细致回复。我很赞同您的意见，LaTex有着无可比拟的优势。
